import type { Metadata, Viewport } from "next";
import { Geist, Geist_Mono, Anton } from "next/font/google";
import localFont from "next/font/local";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// Heavy condensed display face for the project case-study title (ProjectTitleReveal).
const anton = Anton({
  variable: "--font-anton",
  weight: "400", // Anton ships a single weight; it is already display-heavy
  subsets: ["latin"],
});

// Custom display face for the landing hero name (the big "Arif Hasan" title).
const relidux = localFont({
  src: "./fonts/Relidux.otf",
  variable: "--font-relidux",
  display: "swap",
});

// Absolute base for every URL-based metadata field. Without it, Next throws on
// relative metadata URLs and social crawlers get a relative og:image they can't
// fetch. Read from the environment rather than hardcoded so preview deployments
// advertise themselves and not production: Vercel sets
// VERCEL_PROJECT_PRODUCTION_URL on every build, and NEXT_PUBLIC_SITE_URL
// overrides it if a custom domain is ever attached.
const siteUrl =
  process.env.NEXT_PUBLIC_SITE_URL ||
  (process.env.VERCEL_PROJECT_PRODUCTION_URL
    ? `https://${process.env.VERCEL_PROJECT_PRODUCTION_URL}`
    : "http://localhost:3000");

const title = "Arif Hasan";
const description =
  "Arif Hasan — full-stack developer. Portfolio, projects & work.";

export const metadata: Metadata = {
  metadataBase: new URL(siteUrl),
  title,
  description,
  // The share card itself is generated by app/opengraph-image.tsx; these blocks
  // are what make platforms look for it and render it full-bleed rather than as
  // a thumbnail. Previously the site declared neither, so a shared link showed
  // as plain text with no image at all.
  openGraph: {
    type: "website",
    siteName: "Arif Hasan",
    url: siteUrl,
    title,
    description,
  },
  twitter: {
    card: "summary_large_image",
    title,
    description,
  },
  // Standalone / home-screen behavior on iOS: added to the iPhone home screen it
  // shows app/apple-icon.png and opens full-screen (no Safari chrome), like an app.
  appleWebApp: {
    capable: true,
    title: "Arif Hasan",
    statusBarStyle: "black-translucent",
  },
};

// `viewportFit: "cover"` lets the page extend under the notch / home indicator so
// it feels edge-to-edge; components then use env(safe-area-inset-*) to keep chrome
// clear of them. themeColor tints the mobile browser UI black to match the site.
export const viewport: Viewport = {
  themeColor: "#000000",
  width: "device-width",
  initialScale: 1,
  viewportFit: "cover",
};

// Root layout is intentionally MINIMAL: just <html>/<body>, the font variables,
// and global CSS. All the public-site chrome (Navbar, Lenis smooth scroll, the
// pixel-reveal transition, the custom cursor) now lives in the (site) route
// group's layout, so it wraps ONLY the public marketing pages. The /admin app is
// a sibling of (site) and therefore inherits none of it — a clean, plain, fast
// tool UI with a normal cursor and native scrolling. Route groups don't change
// URLs, so the public site's paths are unchanged.
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    // `data-scroll-behavior="smooth"` asks Next.js 16 to restore its pre-16
    // scroll handling during SPA navigations, which cooperates with Lenis
    // instead of fighting it on route changes.
    <html
      lang="en"
      data-scroll-behavior="smooth"
      className={`${geistSans.variable} ${geistMono.variable} ${anton.variable} ${relidux.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">{children}</body>
    </html>
  );
}
